const MIN_VALUE_ADULTS = 1;
const MAX_VALUE_ADULTS = 10;

const MIN_VALUE_CHILD = 0;
const MAX_VALUE_CHILD = 9;

const MIN_VALUE_BABY = 0;
const MAX_VALUE_BABY = 4;

export{
  MIN_VALUE_ADULTS,
  MAX_VALUE_ADULTS,
  MIN_VALUE_CHILD,
  MAX_VALUE_CHILD,
  MIN_VALUE_BABY,
  MAX_VALUE_BABY,
}

